---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-vm-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-vm-csi
