apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-csi2
spec:
  selector:
    matchLabels:
      app: ubuntu-csi2
  replicas: 2
  template:
    metadata:
      labels:
        app: ubuntu-csi2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:20.04
        command:
          - sleep
          - infinity
        volumeMounts:
        - name: ubuntu-csi-data
          mountPath: /mnt
      volumes:
        - name: ubuntu-csi-data
          persistentVolumeClaim:
           claimName: pvc-nfs-vm-dynamic
