Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.ssh.forward_x11 = true

#---------- minikube ----------
  config.vm.define "minikube" do |server|
    server.vm.network "private_network", ip: "192.168.33.10"
    server.vm.hostname = "minikube"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 12288
      vb.cpus = 3
    end
    server.vm.provision "shell", inline: <<-SHELL
      apt update
      #apt install -y ubuntu-desktop 
      apt install -y docker.io
      apt install -y git 
      apt install -y software-properties-common
      apt-add-repository --yes --update ppa:ansible/ansible
      apt install -y ansible
      apt install -y curl
      curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-arm64
      sudo install minikube-linux-arm64 /usr/local/bin/minikube && rm minikube-linux-arm64
      usermod -aG docker vagrant
      cat <<EOF >> /home/vagrant/.bashrc 
alias kubectl="minikube kubectl --"
source <(kubectl completion bash) 
export XAUTHORITY=/home/vagrant/.Xauthority
EOF
      apt install -y bash-completion 
      apt install -y xserver-xorg x11-xserver-utils x11-apps
      cat <<EOF >> /etc/ssh/sshd_config
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost no
EOF
      apt install -y nfs-common
      apt install -y chromium-browser
      #apt install -y xauth xdg-utils snapd
      #apt install -y firefox firefox-locale-ja
    SHELL
  end
#---------- nfs ----------
  config.vm.define "nfs" do |server|
    server.vm.network "private_network", ip: "192.168.33.11"
    server.vm.hostname = "nfs"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y nfs-kernel-server
      mkdir -p /home/vagrant/exports
      chown vagrant:vagrant /home/vagrant/exports
      chmod 777 /home/vagrant/exports
      cat <<EOF >> /etc/exports
/home/vagrant/exports *(rw,nohide,no_subtree_check)
EOF
      exportfs -ra
    SHELL
  end
#-------------------------

end
